using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace PayPalServerSdk.Models;

/// <summary>
/// Customer in merchant's or partner's system of records.
/// </summary>
public record CustomerResponse
{
    /// <summary>
    /// The unique ID for a customer generated by PayPal.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    [StringLength(22, MinimumLength = 1)]
    [RegularExpression("^[0-9a-zA-Z_-]+$")]
    public string? Id { get; init; }

    /// <summary>
    /// Merchants and partners may already have a data-store where their customer information is persisted. Use merchant_customer_id to associate the PayPal-generated customer.id to your representation of a customer.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchant_customer_id")]
    [StringLength(64, MinimumLength = 1)]
    [RegularExpression("^[0-9a-zA-Z-_.^*$@#]+$")]
    public string? MerchantCustomerId { get; init; }
}
