using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace PayPalServerSdk.Models;

/// <summary>
/// This object defines a customer in your system. Use it to manage customer profiles, save payment methods and contact details.
/// </summary>
public record VaultResponseCustomer
{
    /// <summary>
    /// The unique ID for a customer generated by PayPal.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    [StringLength(22, MinimumLength = 1)]
    [RegularExpression("^[0-9a-zA-Z_-]+$")]
    public string? Id { get; init; }

    /// <summary>
    /// Merchants and partners may already have a data-store where their customer information is persisted. Use merchant_customer_id to associate the PayPal-generated customer.id to your representation of a customer.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchant_customer_id")]
    [StringLength(64, MinimumLength = 1)]
    [RegularExpression("^[0-9a-zA-Z-_.^*$@#]+$")]
    public string? MerchantCustomerId { get; init; }

    /// <summary>
    /// DEPRECATED. This field is DEPRECATED.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("links")]
    [MaxLength(16)]
    public IReadOnlyList<object>? Links { get; init; }
}
